name: EconomySystem
api: "1.21"
version: "${version}"
main: com.spectrasonic.economySystem.Main
api-version: "1.21"
authors: [Spectrasonic]
depend: [CommandAPI]
softdepend: [Vault, PlaceholderAPI]

commands:
  balance:
    description: Shows the balance of a player
    usage: /balance [player]
    aliases:
      - bal
      - money
      - pfund
      - coins
      - geld
    permission: economysystem.command.balance
  pay:
    description: Pay a player
    usage: /pay <player> <amount>
    permission: economysystem.command.pay
  economyadmin:
    description: Economy admin commands
    aliases:
      - ecoa
    usage: /economyadmin <set|add|remove> <player> <amount>
    permission: economysystem.command.economyadmin
  balancetop:
    description: Shows the top 10 players with the highest balance
    aliases:
      - baltop
      - topbalance
      - topbal
      - topgeld
    usage: /balancetop
    permission: economysystem.command.balancetop
